<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>Sistema de Recomendación de Libros de Biblioteca</h1>


Utilizado el siguiente modelo :

- Filtrado por Contenido


-> SR con Filtrado basado en Contenido: (ejm: YouTube) Las recomendaciones se  basan en el conocimiento que se tiene sobre los items que el usuario ha valorado (ya sea de forma implícita o explícita), y se le recomendarán items similares que le puedan gustar o interesar.

**Importar Librerias**

---

In [0]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### 1. Importar Data

In [17]:
from google.colab import files
uploaded = files.upload()

Saving historiales.csv to historiales.csv

In [18]:
# import the data
df = pd.read_csv('historiales.csv', sep=';')
df

   1.2.b.- Personas según el hábito de lectura de libros. (%)  ... Unnamed: 16
0                                                 NaN          ...         NaN
1                                                2008          ...         NaN
2                                               Total          ...         NaN
3           Vinculado a la profesión o a los estudios          ...        36.2
4                                   Entre 1 y 3 meses          ...         NaN
5                                   Entre 3 y 6 meses          ...         NaN
6                                   Enre 6 y 12 meses          ...         NaN
7                                     Más de 12 meses          ...         NaN
8                                  Nunca o casi nunca          ...         NaN
9                                               Ns/Nc          ...         NaN
10                                  Vinculado al ocio          ...        68.3
11                                  Entre 1 y 3 meses          ...         NaN
12                                  Entre 3 y 6 meses          ...         NaN
13                                  Enre 6 y 12 meses          ...         NaN
14                                    Más de 12 meses          ...         NaN
15                                 Nunca o casi nunca          ...         NaN
16                                              Ns/Nc          ...         NaN

[17 rows x 17 columns]

In [20]:
df.count()

1.2.b.- Personas según el hábito de lectura de libros. (%)    16
Unnamed: 1                                                    15
Unnamed: 2                                                    15
Unnamed: 3                                                    15
Unnamed: 4                                                    15
Unnamed: 5                                                    15
Unnamed: 6                                                    15
Unnamed: 7                                                    15
Unnamed: 8                                                    15
Unnamed: 9                                                    15
Unnamed: 10                                                   15
Unnamed: 11                                                   15
Unnamed: 12                                                   15
Unnamed: 13                                                   15
Unnamed: 14                                                   15
Unnamed: 15                                                   14
Unnamed: 16                                                    2
dtype: int64

In [25]:
df.head(10)

  1.2.b.- Personas según el hábito de lectura de libros. (%)  ... Unnamed: 16
0                                                NaN          ...         NaN
1                                               2008          ...         NaN
2                                              Total          ...         NaN
3          Vinculado a la profesión o a los estudios          ...        36.2
4                                  Entre 1 y 3 meses          ...         NaN
5                                  Entre 3 y 6 meses          ...         NaN
6                                  Enre 6 y 12 meses          ...         NaN
7                                    Más de 12 meses          ...         NaN
8                                 Nunca o casi nunca          ...         NaN
9                                              Ns/Nc          ...         NaN

[10 rows x 17 columns]

In [26]:
# check types
df.dtypes

1.2.b.- Personas según el hábito de lectura de libros. (%)     object
Unnamed: 1                                                     object
Unnamed: 2                                                     object
Unnamed: 3                                                     object
Unnamed: 4                                                     object
Unnamed: 5                                                     object
Unnamed: 6                                                     object
Unnamed: 7                                                     object
Unnamed: 8                                                     object
Unnamed: 9                                                     object
Unnamed: 10                                                    object
Unnamed: 11                                                    object
Unnamed: 12                                                    object
Unnamed: 13                                                    object
Unnamed: 14                                                    object
Unnamed: 15                                                   float64
Unnamed: 16                                                   float64
dtype: object

In [27]:
df.isnull().sum().sum()

47

In [28]:
# filter by date

df['cohort_date'] = pd.to_datetime(df['cohort_date'])
filtro_date = '17-09-2016'
mask = (df['cohort_date'] > filtro_date)
df = df.loc[mask]
df

KeyError: ignored